### PR TITLE
Deno publish fix

### LINKED ISSUE #97: postcss_nesting doesn't work on Deno
I have this error importing the plugin in this way:

```js
import postcssNesting from "https://cdn.jsdelivr.net/gh/csstools/postcss-nesting@10.0.1/mod.js";
```
It works fine in `9.0.0`.

In adddition to that, the README says that it can be imported from deno.land/x (`import postcssNesting from "https://deno.land/x/postcss_nesting/mod.js";`), but [the module is not registered there](https://deno.land/x/postcss_nesting/mod.js)

### PR DESCRIPTION
**Pull request by Antonio-Laguna**
Fixes #97

### CODE REVIEW

**Comment by romainmenke** [comment]
I noticed that we forgot to include `test:deno` in `test` in package.json
Maybe this :

```json
    "test": "node .bin/test.js && npm run test:deno",
```

**Comment by Antonio-Laguna** [comment]
@romainmenke I thought about that too but this requires you always have `deno` installed to do tests. Thoughts on this?

**Comment by romainmenke** [comment]
@Antonio-Laguna agreed.
We have it in CI as a separate step so we get a signal if it fails.

**Review by romainmenke — APPROVED** [review]
LGTM!

**Pull request merged**
